name: Black

on: 
  push:
    branches:
      - '!master'

jobs:
  format-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
    
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.12.1
    
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
    
    - name: Run Black
      run: |
        black --diff src/
        black --check --verbose src/
