name: Black Diff

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1
    
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
    
    - name: Run Black
      run: |
        black --diff src/
        black --check --verbose src/
